### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by TheRealJohnnySteele** [JDCalvert/FVTT-PF2e-Ranged-Combat#176]
Getting that message whenever trying to reload. Created a new, blank PF2e world. Activated pf2e Ranged Combat and libwrapper. Imported the iconics, dropped Harsk Level 5 on a blank scene. Made sure his arbalast was equipped and had ammo assigned to it. Hit 'reload' and got the message.

Log shows the following:
Cannot read properties of undefined (reading 'length')
fetch @ foundry.js:68326
utils.js:106 Uncaught (in promise) TypeError: undefined. Cannot read properties of undefined (reading 'length')
[No packages detected]
    at Preprocessor.advance (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/preprocessor.js:138:35)
    at Tokenizer._consume (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/index.js:270:34)
    at Tokenizer._runParsingLoop (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/index.js:221:29)
    at Tokenizer.write (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/tokenizer/index.js:248:14)
    at parseFragment (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/node_modules/parse5/dist/index.js:42:22)
    at cleanHTML (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/validators.mjs:1:209)
    at HTMLField.sanitizeHTMLField [as sanitize] (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/sanitization.mjs:1:1235)
    at Item._sanitizeFields (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:7729)
    at Item._sanitizeFields (/C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/database/backend/server-document.mjs:1:7956)

**Comment by JDCalvert** [comment]
I haven't been able to replicate this. It sounds like either an install issue or something else.. weird. It doesn't mention the module at all. Please reinstall, try again, and see if the issue persists.

**Comment by JDCalvert** [comment]
It's been two weeks with no reply, so closing this. Please re-open if the problem happens again.
