### ISSUE TITLE
Error when using reload macro

### ISSUE THREAD

**Issue by Zamrod** [JDCalvert/FVTT-PF2e-Ranged-Combat#7]
When you attempt to use the reload macro in version 2.0 you get the following error:

```
reload.js:143 
        
       Uncaught (in promise) TypeError: PF2eRangedCombat.requiredLoading is not a function
[Detected 1 package: pf2e-ranged-combat]
    at reload.js:143:48
    at Array.filter (<anonymous>)
    at getReloadableWeapons (reload.js:143:14)
    at Object.reload (reload.js:24:57)
    at eval (eval at _executeScript (foundry.js:16907:16), <anonymous>:4:29)
    at MacroPF2e.eval (eval at _executeScript (foundry.js:16907:16), <anonymous>:5:7)
    at MacroPF2e._executeScript (foundry.js:16909:10)
    at MacroPF2e.execute (foundry.js:16866:21)
    at Hotbar._onClickMacro (foundry.js:52252:20)
    at HTMLLIElement.dispatch (jquery.min.js:2:43064)
    at HTMLLIElement.v.handle (jquery.min.js:2:41048)
```

**Comment by JDCalvert** [comment]
Thank you for reporting this issue. Should be fixed as of version 2.0.1.
